xilplmi: xplmi_plat.c File Reference
net/xplmi_plat.c File Reference
Overview
This file contains the PLMI versal_net platform specific code.
MODIFICATION HISTORY:
Ver   Who  Date        Changes
----- ---- -------- -------------------------------------------------------
1.00  bm   07/06/2022 Initial release
      dc   07/12/2022 Added XPlmi_RomISR() API
      kpt  07/21/2022 Added KAT APIs
      bm   07/22/2022 Update EAM logic for In-Place PLM Update
      bm   07/22/2022 Retain critical data structures after In-Place PLM Update
      bm   07/22/2022 Shutdown modules gracefully during update
1.01  bm   11/07/2022 Clear SSS Cfg Error in SSSCfgSbiDma for Versal Net
      ng   11/11/2022 Fixed doxygen file name error
      kpt  01/04/2023 Added XPlmi_CheckandUpdateFipsState to update FIPS state
Note
Macros
#define XPLMI_ROM_VERSION_1_0 (0x10U)
ROM version 1.
Functions
XInterruptHandler * XPlmi_GetTopLevelIntrTbl (void)
This function provides pointer to g_TopLevelInterruptTable.
u8 XPlmi_GetTopLevelIntrTblSize (void)
This function provides size of g_TopLevelInterruptTable.
XPlmi_BoardParams * XPlmi_GetBoardParams (void)
This function provides pointer to BoardParams.
u32 * XPlmi_GetLpdInitialized (void)
This function provides LpdInitialized variable pointer.
u32 * XPlmi_GetUartBaseAddr (void)
This function provides LpdInitialized variable pointer.
void XPlmi_PreInit (void)
This function performs plmi pre-initializaton.
void XPlmi_RtcaPlatInit (void)
This function performs initialization of platform specific RCTA registers.
void XPlmi_PrintRomVersion (void)
This function prints ROM version using ROM digest value.
void XPlmi_SssMask (u32 InputSrc, u32 OutputSrc)
This function masks the secure stream switch value.
XPlmi_CircularBuffer * XPlmi_GetTraceLogInst (void)
This function provides TraceLog instance.
int XPlmi_GenericHandler (XPlmi_ModuleOp Op)
This function is used for shutdown operation before In-place PLM Update.
void XPlmi_GetReadbackSrcDest (u32 SlrType, u64 *SrcAddr, u64 *DestAddrRead)
This function processes and provides SrcAddr and DestAddr for cfi readback.
void XPlmi_GicAddTask (u32 PlmIntrId)
This will add the GIC interrupt task handler to the TaskQueue.
void XPlmi_IpiIntrHandler (void *CallbackRef)
This function is the Ipi interrupt handler for the device.
int XPlmi_RegisterNEnableIpi (void)
This function registers and enables IPI interrupt.
void XPlmi_EnableIomoduleIntr (void)
This function registers and enables IPI interrupt.
int XPlmi_SetPmcIroFreq (void)
It sets the PMC IRO frequency.
int XPlmi_GetPitResetValues (u32 *Pit1ResetValue, u32 *Pit2ResetValue)
This functions provides the PIT1 and PIT2 reset values.
int XPlmi_VerifyAddrRange (u64 StartAddr, u64 EndAddr)
This function is used to check if the given address range is valid.
XPlmi_WaitForDmaDone_t XPlmi_GetPlmiWaitForDone (u64 DestAddr)
This function is used to check and wait for DMA done.
u32 XPlmi_GetGicIntrId (u32 GicPVal, u32 GicPxVal)
This function provides Gic interrupt id.
u32 XPlmi_GetIpiIntrId (u32 BufferIndex)
This function provides IPI interrupt id.
int XPlmi_RomISR (XPlmi_RomIntr RomServiceReq)
This function raises an interrupt request to ROM and waits for completion.
u8 XPlmi_IsFipsModeEn (void)
This function return FIPS mode.
u32 XPlmi_GetRomKatStatus (void)
This function returns ROM KAT status.
void XPlmi_GetBootKatStatus (volatile u32 *PlmKatStatus)
This function sets KAT status from RTC area.
void XPlmi_ClearSSSCfgErr (void)
This function clears SSS Cfg error set during ROM PCR Extension.
XPlmi_FipsKatMask * XPlmi_GetFipsKatMaskInstance (void)
This function returns XPlmi_FipsKatMask instance.
int XPlmi_CheckAndUpdateFipsState (void)
This function checks and updates the FIPS state in RTCA.
void XPlmi_UpdateCryptoStatus (u32 Mask, u32 Val)
This function sets or clears crypto bit in RTCA based on mask.
u32 XPlmi_GetCryptoStatus (u32 Mask)
This function returns crypto status flag.
Macro Definition Documentation
#define XPLMI_ROM_VERSION_1_0 (0x10U)
ROM version 1.
Referenced by XPlmi_PrintRomVersion().
Function Documentation
int XPlmi_CheckAndUpdateFipsState (void)
This function checks and updates the FIPS state in RTCA.
Returns
XST_SUCCESS on Success XST_FAILURE on Failure
References XPlmi_CheckAndUpdateFipsState(), and XPlmi_IsFipsModeEn().
Referenced by XPlmi_CheckAndUpdateFipsState(), XPlmi_SetFipsKatMask(), and XPlmi_UpdateKatStatus().
void XPlmi_ClearSSSCfgErr (void)
This function clears SSS Cfg error set during ROM PCR Extension.
Returns
None
References XPlmi_ClearSSSCfgErr(), and XPlmi_IsPlmUpdateDone().
Referenced by XPlmi_ClearSSSCfgErr().
void XPlmi_EnableIomoduleIntr (void)
This function registers and enables IPI interrupt.
Returns
None
References XPlmi_PlmIntrEnable().
int XPlmi_GenericHandler (XPlmi_ModuleOp Op)
This function is used for shutdown operation before In-place PLM Update.
Parameters
Op is the operation information
Returns
XST_SUCCESS on success and XST_FAILURE on failure
References EmDisableErrAction(), XPlmi_EmDisablePsmErrors(), XPlmi_GicIntrClearStatus(), XPlmi_PlmIntrClear(), and XPlmi_PlmIntrDisable().
XPlmi_BoardParams* XPlmi_GetBoardParams (void)
This function provides pointer to BoardParams.
Returns
Pointer to BoardParams
void XPlmi_GetBootKatStatus (volatile u32 * PlmKatStatus)
This function sets KAT status from RTC area.
This function returns KAT status from RCTA area.
Parameters
PlmKatStatus is the pointer to the variable which holds kat status
Returns
None
References XPlmi_GetKatStatus(), XPlmi_GetRomKatStatus(), XPlmi_IsCryptoKatEn(), XPlmi_IsFipsModeEn(), and XPlmi_UpdateKatStatus().
u32 XPlmi_GetCryptoStatus (u32 Mask)
This function returns crypto status flag.
Parameters
Mask Mask to read crypto status
Returns
Crypto status value
XPlmi_FipsKatMask* XPlmi_GetFipsKatMaskInstance (void)
This function returns XPlmi_FipsKatMask instance.
Returns
pointer to the XPlmi_FipsKatMask instance
Referenced by XPlmi_SetFipsKatMask().
u32 XPlmi_GetGicIntrId (u32 GicPVal, u32 GicPxVal)
This function provides Gic interrupt id.
Parameters
GicPVal indicates GICP source
GicPxVal indicates GICPx source
Returns
Readback length
u32 XPlmi_GetIpiIntrId (u32 BufferIndex)
This function provides IPI interrupt id.
Parameters
BufferIndex is the Ipi target buffer index
Returns
IPI interrupt id
u32* XPlmi_GetLpdInitialized (void)
This function provides LpdInitialized variable pointer.
Returns
Pointer to LpdInitialized variable
int XPlmi_GetPitResetValues (u32 * Pit1ResetValue, u32 * Pit2ResetValue)
This functions provides the PIT1 and PIT2 reset values.
Returns
XST_SUCCESS
References XPLMI_ERR_IOMOD_INIT, and XPlmi_IsPlmUpdateDone().
XPlmi_WaitForDmaDone_t XPlmi_GetPlmiWaitForDone (u64 DestAddr)
This function is used to check and wait for DMA done.
This function is used to check and wait for DMA done when sending data to SSIT Slave SLRs.
Parameters
DmaPtr is pointer to DMA structure
Channel is DMA source or destination channel
Returns
XST_SUCCESS on success and error code on failure
void XPlmi_GetReadbackSrcDest (u32 SlrType, u64 * SrcAddr, u64 * DestAddrRead)
This function processes and provides SrcAddr and DestAddr for cfi readback.
Parameters
SlrType is the type of Slr passed in readback cmd
SrcAddr is the pointer to the SrcAddr variable
DestAddrRead is the pointer to the DestAddrRead variable
Returns
None
u32 XPlmi_GetRomKatStatus (void)
This function returns ROM KAT status.
Returns
ROM KAT status
Referenced by XPlmi_GetBootKatStatus().
XInterruptHandler* XPlmi_GetTopLevelIntrTbl (void)
This function provides pointer to g_TopLevelInterruptTable.
Returns
Pointer to g_TopLevelInterruptTable structure
u8 XPlmi_GetTopLevelIntrTblSize (void)
This function provides size of g_TopLevelInterruptTable.
Returns
Size g_TopLevelInterruptTable structure
XPlmi_CircularBuffer* XPlmi_GetTraceLogInst (void)
This function provides TraceLog instance.
Returns
Pointer to TraceLog variable
u32* XPlmi_GetUartBaseAddr (void)
This function provides LpdInitialized variable pointer.
Returns
Pointer to LpdInitialized variable
< Base address of Uart
void XPlmi_GicAddTask (u32 PlmIntrId)
This will add the GIC interrupt task handler to the TaskQueue.
Parameters
PlmIntrId is the GIC interrupt ID of the task
Returns
None
References XPlmi_GetIpiIntrId(), and XPlmi_GicIntrAddTask().
void XPlmi_IpiIntrHandler (void * CallbackRef)
This function is the Ipi interrupt handler for the device.
Parameters
CallbackRef is a dummy argument
Returns
None
References XPlmi_GetIpiIntrId(), XPlmi_GetTaskInstance(), XPlmi_IpiIntrHandler(), XPlmi_PlmIntrClear(), and XPlmi_TaskTriggerNow().
Referenced by XPlmi_IpiIntrHandler(), and XPlmi_RegisterNEnableIpi().
u8 XPlmi_IsFipsModeEn (void)
This function return FIPS mode.
Returns
TRUE If FIPS mode is enabled FALSE If FIPS mode is disabled
Referenced by XPlmi_CheckAndUpdateFipsState(), and XPlmi_GetBootKatStatus().
void XPlmi_PreInit (void)
This function performs plmi pre-initializaton.
Returns
None
References XPlmi_IsPlmUpdateDone(), and XPlmi_RestoreWdt().
void XPlmi_PrintRomVersion (void)
This function prints ROM version using ROM digest value.
Returns
None
References XPLMI_ROM_VERSION_1_0.
int XPlmi_RegisterNEnableIpi (void)
This function registers and enables IPI interrupt.
Returns
XST_SUCCESS on success and XST_FAILURE on failure
References XPlmi_IpiIntrHandler(), XPlmi_PlmIntrEnable(), and XPlmi_RegisterHandler().
int XPlmi_RomISR (XPlmi_RomIntr RomServiceReq)
This function raises an interrupt request to ROM and waits for completion.
Before calling this API all pre-requsites for ROM service shall be completed.
Parameters
RomServiceReq variable of enum type XPlmi_RomIntr
Returns
XST_SUCCESS - If the ROM interrupt service completes
XST_FAILURE - Upon any failure
References XPLMI_DME_CHL_SIGN_GEN, XPLMI_ERR_INVALID_ROM_INT_REQ, XPLMI_INVALID_INT, and XPLMI_PLM_UPDT_REQ.
void XPlmi_RtcaPlatInit (void)
This function performs initialization of platform specific RCTA registers.
Returns
None
int XPlmi_SetPmcIroFreq (void)
It sets the PMC IRO frequency.
Returns
XST_SUCCESS on success and error code failure
References XPlmi_GetPmcIroFreq().
void XPlmi_SssMask (u32 InputSrc, u32 OutputSrc)
This function masks the secure stream switch value.
Parameters
InputSrc - Input source to be selected for the resource
OutputSrc - Output source to be selected for the resource
References XPlmi_SssMask().
Referenced by XPlmi_SssMask().
void XPlmi_UpdateCryptoStatus (u32 Mask, u32 Val)
This function sets or clears crypto bit in RTCA based on mask.
Parameters
Mask Mask to set or clear crypto status
Val Value to set or clear crypto status
References XPlmi_UtilRMW().
int XPlmi_VerifyAddrRange (u64 StartAddr, u64 EndAddr)
This function is used to check if the given address range is valid.
This function can be called before loading any elf or assigning any buffer in that address range
Parameters
StartAddr is the starting address
EndAddr is the ending address
Returns
XST_SUCCESS on success and error code on failure