xilplmi: xplmi_plat.h File Reference
xplmi_plat.h File Reference
Overview
This file contains declarations of versal specific APIs.
MODIFICATION HISTORY:
Ver   Who  Date        Changes
----- ---- -------- -------------------------------------------------------
1.00  bm   07/06/2022 Initial release
      ma   07/08/2022 Add ScatterWrite and ScatterWrite2 commands to versal
      is   07/19/2022 Add HBM temperature monitoring registers from RTCA
      kpt  07/21/2022 Added API and macros related to KAT
      bm   07/22/2022 Update EAM logic for In-Place PLM Update
      bm   07/22/2022 Added compatibility check for In-Place PLM Update
      bm   07/22/2022 Retain critical data structures after In-Place PLM Update
      bm   07/22/2022 Shutdown modules gracefully during update
      bm   09/14/2022 Move ScatterWrite commands from common to versal_net
1.01  bm   11/07/2022 Clear SSS Cfg Error in SSSCfgSbiDma for Versal Net
      ng   11/11/2022 Fixed doxygen file name error
      bm   01/03/2023 Notify Other SLRs about Secure Lockdown
      sk   01/11/2023 Added Config Space for Image Store in RTCA
      bm   01/18/2023 Fix CFI readback logic with correct keyhole size
Note
Macros
#define XPLMI_GICP0_SRC13 (13U)
GPIO Interrupt.
#define XPLMI_GICP0_SRC14 (14U)
I2C_0 Interrupt.
#define XPLMI_GICP0_SRC15 (15U)
I2C_1 Interrupt.
#define XPLMI_GICP0_SRC16 (16U)
SPI_0 Interrupt.
#define XPLMI_GICP0_SRC17 (17U)
SPI_1 Interrupt.
#define XPLMI_GICP0_SRC18 (18U)
UART_0 Interrupt.
#define XPLMI_GICP0_SRC19 (19U)
UART_1 Interrupt.
#define XPLMI_GICP0_SRC20 (20U)
CAN_0 Interrupt.
#define XPLMI_GICP0_SRC21 (21U)
CAN_1 Interrupt.
#define XPLMI_GICP0_SRC22 (22U)
USB_0 Interrupt.
#define XPLMI_GICP0_SRC23 (23U)
USB_0 Interrupt.
#define XPLMI_GICP0_SRC24 (24U)
USB_0 Interrupt.
#define XPLMI_GICP0_SRC25 (25U)
USB_0 Interrupt.
#define XPLMI_GICP0_SRC26 (26U)
USB_0 Interrupt.
#define XPLMI_GICP0_SRC27 (27U)
IPI Interrupt.
#define XPLMI_GICP1_SRC5 (5U)
TTC_0 Interrupt.
#define XPLMI_GICP1_SRC6 (6U)
TTC_0 Interrupt.
#define XPLMI_GICP1_SRC7 (7U)
TTC_0 Interrupt.
#define XPLMI_GICP1_SRC8 (8U)
TTC_1 Interrupt.
#define XPLMI_GICP1_SRC9 (9U)
TTC_1 Interrupt.
#define XPLMI_GICP1_SRC10 (10U)
TTC_1 Interrupt.
#define XPLMI_GICP1_SRC11 (11U)
TTC_2 Interrupt.
#define XPLMI_GICP1_SRC12 (12U)
TTC_2 Interrupt.
#define XPLMI_GICP1_SRC13 (13U)
TTC_2 Interrupt.
#define XPLMI_GICP1_SRC14 (14U)
TTC_3 Interrupt.
#define XPLMI_GICP1_SRC15 (15U)
TTC_3 Interrupt.
#define XPLMI_GICP1_SRC16 (16U)
TTC_3 Interrupt.
#define XPLMI_GICP1_SRC24 (24U)
GEM_0 Interrupt.
#define XPLMI_GICP1_SRC25 (25U)
GEM_0 Interrupt.
#define XPLMI_GICP1_SRC26 (26U)
GEM_1 Interrupt.
#define XPLMI_GICP1_SRC27 (27U)
GEM_1 Interrupt.
#define XPLMI_GICP1_SRC28 (28U)
ADMA_0 Interrupt.
#define XPLMI_GICP1_SRC29 (29U)
ADMA_1 Interrupt.
#define XPLMI_GICP1_SRC30 (30U)
ADMA_2 Interrupt.
#define XPLMI_GICP1_SRC31 (31U)
ADMA_3 Interrupt.
#define XPLMI_GICP2_SRC0 (0U)
ADMA_4 Interrupt.
#define XPLMI_GICP2_SRC1 (1U)
ADMA_5 Interrupt.
#define XPLMI_GICP2_SRC2 (2U)
ADMA_6 Interrupt.
#define XPLMI_GICP2_SRC3 (3U)
ADMA_7 Interrupt.
#define XPLMI_GICP2_SRC10 (10U)
USB_0 Interrupt.
#define XPLMI_GICP3_SRC30 (30U)
SD_0 Interrupt.
#define XPLMI_GICP3_SRC31 (31U)
SD_0 Interrupt.
#define XPLMI_GICP4_SRC0 (0U)
SD_1 Interrupt.
#define XPLMI_GICP4_SRC1 (1U)
SD_1 Interrupt.
#define XPLMI_GICP4_SRC8 (8U)
SBI interrupt.
#define XPLMI_GICP4_SRC14 (14U)
RTC interrupt.
Enumerations
enum { XPLMI_ERR_CURRENT_UART_INVALID = 0x2, XPLMI_ERR_INVALID_UART_SELECT, XPLMI_ERR_INVALID_UART_ENABLE, XPLMI_ERR_NO_UART_PRESENT }
Functions
u32 * XPlmi_GetLpdInitialized (void)
This function provides LpdInitialized variable pointer.
void XPlmi_RtcaPlatInit (void)
This function performs initialization of platform specific RCTA registers.
void XPlmi_PrintRomVersion (void)
This function prints ROM version using ROM digest value.
void XPlmi_PreInit (void)
This function performs plmi pre-initializaton.
XPlmi_WaitForDmaDone_t XPlmi_GetPlmiWaitForDone (u64 DestAddr)
This function is used to check and wait for DMA done when sending data to SSIT Slave SLRs.
XPlmi_CircularBuffer * XPlmi_GetTraceLogInst (void)
This function provides TraceLog instance.
void XPlmi_GetReadbackSrcDest (u32 SlrType, u64 *SrcAddr, u64 *DestAddrRead)
This function processes and provides SrcAddr and DestAddr for cfi readback.
void XPlmi_GicAddTask (u32 PlmIntrId)
This will add the GIC interrupt task handler to the TaskQueue.
XInterruptHandler * XPlmi_GetTopLevelIntrTbl (void)
This function provides pointer to g_TopLevelInterruptTable.
u8 XPlmi_GetTopLevelIntrTblSize (void)
This function provides size of g_TopLevelInterruptTable.
int XPlmi_RegisterNEnableIpi (void)
This function registers and enables IPI interrupt.
void XPlmi_EnableIomoduleIntr (void)
This function registers and enables IPI interrupt.
int XPlmi_SetPmcIroFreq (void)
It sets the PMC IRO frequency.
int XPlmi_GetPitResetValues (u32 *Pit1ResetValue, u32 *Pit2ResetValue)
This functions provides the PIT1 and PIT2 reset values.
int XPlmi_VerifyAddrRange (u64 StartAddr, u64 EndAddr)
This function is used to check if the given address range is valid.
u32 XPlmi_GetGicIntrId (u32 GicPVal, u32 GicPxVal)
This function provides Gic interrupt id.
u32 XPlmi_GetIpiIntrId (u32 BufferIndex)
This function provides IPI interrupt id.
void XPlmi_EnableIpiIntr (void)
This function enables IPI interrupt.
void XPlmi_ClearIpiIntr (void)
This function clears IPI interrupt.
void XPlmi_DisableCFrameIso (void)
This function Disables CFRAME Isolation.
u32 * XPlmi_GetUartBaseAddr (void)
This function provides LpdInitialized variable pointer.
void XPlmi_GetBootKatStatus (volatile u32 *PlmKatStatus)
This function returns KAT status from RCTA area.
void XPlmi_NotifySldSlaveSlrs (void)
This function notifies other SLRs about Secure Lockdown or tamper condition in SSIT devices.
void XPlmi_InterSlrSldHandshake (void)
This function performs handshake between SLRs on SSIT ERR lines.
int XPlmi_CheckIpiAccess (u32 CmdId, u32 IpiReqType)
This function checks if the IPI command is accessible or not.
int XPlmi_ValidateCmd (u32 ModuleId, u32 ApiId)
This function checks whether the Cmd passed is supported via IPI mechanism or not.
Macro Definition Documentation
#define XPLMI_GICP0_SRC13 (13U)
GPIO Interrupt.
#define XPLMI_GICP0_SRC14 (14U)
I2C_0 Interrupt.
#define XPLMI_GICP0_SRC15 (15U)
I2C_1 Interrupt.
#define XPLMI_GICP0_SRC16 (16U)
SPI_0 Interrupt.
#define XPLMI_GICP0_SRC17 (17U)
SPI_1 Interrupt.
#define XPLMI_GICP0_SRC18 (18U)
UART_0 Interrupt.
#define XPLMI_GICP0_SRC19 (19U)
UART_1 Interrupt.
#define XPLMI_GICP0_SRC20 (20U)
CAN_0 Interrupt.
#define XPLMI_GICP0_SRC21 (21U)
CAN_1 Interrupt.
#define XPLMI_GICP0_SRC22 (22U)
USB_0 Interrupt.
#define XPLMI_GICP0_SRC23 (23U)
USB_0 Interrupt.
#define XPLMI_GICP0_SRC24 (24U)
USB_0 Interrupt.
#define XPLMI_GICP0_SRC25 (25U)
USB_0 Interrupt.
#define XPLMI_GICP0_SRC26 (26U)
USB_0 Interrupt.
#define XPLMI_GICP0_SRC27 (27U)
IPI Interrupt.
#define XPLMI_GICP1_SRC10 (10U)
TTC_1 Interrupt.
#define XPLMI_GICP1_SRC11 (11U)
TTC_2 Interrupt.
#define XPLMI_GICP1_SRC12 (12U)
TTC_2 Interrupt.
#define XPLMI_GICP1_SRC13 (13U)
TTC_2 Interrupt.
#define XPLMI_GICP1_SRC14 (14U)
TTC_3 Interrupt.
#define XPLMI_GICP1_SRC15 (15U)
TTC_3 Interrupt.
#define XPLMI_GICP1_SRC16 (16U)
TTC_3 Interrupt.
#define XPLMI_GICP1_SRC24 (24U)
GEM_0 Interrupt.
#define XPLMI_GICP1_SRC25 (25U)
GEM_0 Interrupt.
#define XPLMI_GICP1_SRC26 (26U)
GEM_1 Interrupt.
#define XPLMI_GICP1_SRC27 (27U)
GEM_1 Interrupt.
#define XPLMI_GICP1_SRC28 (28U)
ADMA_0 Interrupt.
#define XPLMI_GICP1_SRC29 (29U)
ADMA_1 Interrupt.
#define XPLMI_GICP1_SRC30 (30U)
ADMA_2 Interrupt.
#define XPLMI_GICP1_SRC31 (31U)
ADMA_3 Interrupt.
#define XPLMI_GICP1_SRC5 (5U)
TTC_0 Interrupt.
#define XPLMI_GICP1_SRC6 (6U)
TTC_0 Interrupt.
#define XPLMI_GICP1_SRC7 (7U)
TTC_0 Interrupt.
#define XPLMI_GICP1_SRC8 (8U)
TTC_1 Interrupt.
#define XPLMI_GICP1_SRC9 (9U)
TTC_1 Interrupt.
#define XPLMI_GICP2_SRC0 (0U)
ADMA_4 Interrupt.
#define XPLMI_GICP2_SRC1 (1U)
ADMA_5 Interrupt.
#define XPLMI_GICP2_SRC10 (10U)
USB_0 Interrupt.
#define XPLMI_GICP2_SRC2 (2U)
ADMA_6 Interrupt.
#define XPLMI_GICP2_SRC3 (3U)
ADMA_7 Interrupt.
#define XPLMI_GICP3_SRC30 (30U)
SD_0 Interrupt.
#define XPLMI_GICP3_SRC31 (31U)
SD_0 Interrupt.
#define XPLMI_GICP4_SRC0 (0U)
SD_1 Interrupt.
#define XPLMI_GICP4_SRC1 (1U)
SD_1 Interrupt.
#define XPLMI_GICP4_SRC14 (14U)
RTC interrupt.
#define XPLMI_GICP4_SRC8 (8U)
SBI interrupt.
Enumeration Type Documentation
anonymous enum
Enumerator
XPLMI_ERR_CURRENT_UART_INVALID
0x2 - Error when current uart selected has invalid base address
XPLMI_ERR_INVALID_UART_SELECT
0x3 - Error when invalid uart select argument is passed
XPLMI_ERR_INVALID_UART_ENABLE
0x4 - Error when invalid uart enable argument is passed
XPLMI_ERR_NO_UART_PRESENT
0x5 - Error when no uart is present to configure in run-time
Function Documentation
void XPlmi_ClearIpiIntr (void)
This function clears IPI interrupt.
Returns
None
void XPlmi_DisableCFrameIso (void)
This function Disables CFRAME Isolation.
Returns
None
References XPlmi_UtilRMW().
void XPlmi_EnableIomoduleIntr (void)
This function registers and enables IPI interrupt.
Returns
None
void XPlmi_EnableIpiIntr (void)
This function enables IPI interrupt.
Returns
None
void XPlmi_GetBootKatStatus (volatile u32 * PlmKatStatus)
This function returns KAT status from RCTA area.
Parameters
PlmKatStatus is the pointer to the variable which holds kat status
Returns
None
This function returns KAT status from RCTA area.
Parameters
PlmKatStatus is the pointer to the variable which holds kat status
Returns
None
u32 XPlmi_GetGicIntrId (u32 GicPVal, u32 GicPxVal)
This function provides Gic interrupt id.
Parameters
GicPVal indicates GICP source
GicPxVal indicates GICPx source
Returns
Gic Interrupt Id
Parameters
GicPVal indicates GICP source
GicPxVal indicates GICPx source
Returns
Readback length
u32 XPlmi_GetIpiIntrId (u32 BufferIndex)
This function provides IPI interrupt id.
Parameters
BufferIndex is the Ipi target buffer index
Returns
IPI interrupt id
u32* XPlmi_GetLpdInitialized (void)
This function provides LpdInitialized variable pointer.
Returns
Pointer to LpdInitialized variable
int XPlmi_GetPitResetValues (u32 * Pit1ResetValue, u32 * Pit2ResetValue)
This functions provides the PIT1 and PIT2 reset values.
Returns
XST_SUCCESS
XPlmi_WaitForDmaDone_t XPlmi_GetPlmiWaitForDone (u64 DestAddr)
This function is used to check and wait for DMA done when sending data to SSIT Slave SLRs.
Parameters
DmaPtr is pointer to DMA structure
Channel is DMA source or destination channel
Returns
XST_SUCCESS on success and error code on failure
This function is used to check and wait for DMA done when sending data to SSIT Slave SLRs.
Parameters
DmaPtr is pointer to DMA structure
Channel is DMA source or destination channel
Returns
XST_SUCCESS on success and error code on failure
void XPlmi_GetReadbackSrcDest (u32 SlrType, u64 * SrcAddr, u64 * DestAddrRead)
This function processes and provides SrcAddr and DestAddr for cfi readback.
Parameters
SlrType is the type of Slr passed in readback cmd
SrcAddr is the pointer to the SrcAddr variable
DestAddrRead is the pointer to the DestAddrRead variable
Returns
None
XInterruptHandler* XPlmi_GetTopLevelIntrTbl (void)
This function provides pointer to g_TopLevelInterruptTable.
Returns
Pointer to g_TopLevelInterruptTable structure
u8 XPlmi_GetTopLevelIntrTblSize (void)
This function provides size of g_TopLevelInterruptTable.
Returns
Size g_TopLevelInterruptTable structure
XPlmi_CircularBuffer* XPlmi_GetTraceLogInst (void)
This function provides TraceLog instance.
Returns
Pointer to TraceLog variable
u32* XPlmi_GetUartBaseAddr (void)
This function provides LpdInitialized variable pointer.
Returns
Pointer to LpdInitialized variable
< Base address of Uart
< Base address of Uart
void XPlmi_GicAddTask (u32 PlmIntrId)
This will add the GIC interrupt task handler to the TaskQueue.
Parameters
PlmIntrId is the GIC interrupt ID of the task
Returns
None
void XPlmi_InterSlrSldHandshake (void)
This function performs handshake between SLRs on SSIT ERR lines.
    This has to be done on SSIT devices before doing secure lockdown
Returns
None
References XPlmi_UtilPoll(), XPlmi_UtilPollForMask(), and XPlmi_UtilPollNs().
void XPlmi_NotifySldSlaveSlrs (void)
This function notifies other SLRs about Secure Lockdown or tamper condition in SSIT devices.
Returns
None
Referenced by XPlmi_TriggerTamperResponse().
void XPlmi_PreInit (void)
This function performs plmi pre-initializaton.
Returns
None
void XPlmi_PrintRomVersion (void)
This function prints ROM version using ROM digest value.
Returns
None
int XPlmi_RegisterNEnableIpi (void)
This function registers and enables IPI interrupt.
Returns
XST_SUCCESS on success and XST_FAILURE on failure
void XPlmi_RtcaPlatInit (void)
This function performs initialization of platform specific RCTA registers.
Returns
None
int XPlmi_SetPmcIroFreq (void)
It sets the PMC IRO frequency.
Returns
XST_SUCCESS on success and error code failure
int XPlmi_VerifyAddrRange (u64 StartAddr, u64 EndAddr)
This function is used to check if the given address range is valid.
This function can be called before loading any elf or assigning any buffer in that address range
Parameters
StartAddr is the starting address
EndAddr is the ending address
Returns
XST_SUCCESS on success and error code on failure