xilplmi: xplmi_update.c File Reference
xplmi_update.c File Reference
Overview
This is the file which contains PLM update process.
This code in this file is applicable only for versal_net platform.
MODIFICATION HISTORY:
Ver   Who  Date       Changes
----- ---- ---------- -------------------------------------------------------
1.00  bm   01/30/2022 Initial release
      bm   07/06/2022 Refactor versal and versal_net code
      bm   07/13/2022 Added compatibility check for In-Place PLM Update
      bm   07/18/2022 Shutdown modules gracefully during update
1.01  ng   11/11/2022 Fixed doxygen file name error
Note
Functions
u8 XPlmi_IsPlmUpdateDone (void)
This function checks if Inplace PLM update occurs or not.
u8 XPlmi_IsPlmUpdateInProgress (void)
This function checks if Inplace PLM update is in progress or not.
int XPlmi_DsOps (u32 Op, u64 Addr, void *Data)
This function does operations like storing, restoring the Data Structure to Memory during PLM update.
XPlmi_DsEntry * XPlmi_GetDsEntry (XPlmi_DsEntry *DsList, u32 DsCnt, XPlmi_DsVer *DsVer)
This function returns DsEntry found after searching in the provided DsList.
int XPlmi_RestoreDataBackup (void)
This function restore all the data structures after InPlace PLM udpate.
int XPlmi_PlmUpdate (XPlmi_Cmd *Cmd)
This function does In-Place PLM Update.
Function Documentation
int XPlmi_DsOps (u32 Op, u64 Addr, void * Data)
This function does operations like storing, restoring the Data Structure to Memory during PLM update.
Parameters
Op is the type of operation to be performed on the data structure
Addr is the memory address to which data structure should be stored or restored from
Data is the Data Structure Entry
Returns
XST_SUCCESS on success and error code on failure
References XPLMI_ERR_DS_ALIGNMENT_INCORRECT, XPLMI_ERR_INVALID_DS_ENTRY, XPLMI_ERR_MEMCPY_RESTORE_DB, XPLMI_ERR_MEMCPY_STORE_DB, XPLMI_ERR_MEMSET_RESTORE_DB, XPLMI_ERR_PLM_UPDATE_DB_OVERFLOW, and XPLMI_ERR_PLM_UPDATE_INVALID_OP.
XPlmi_DsEntry* XPlmi_GetDsEntry (XPlmi_DsEntry * DsList, u32 DsCnt, XPlmi_DsVer * DsVer)
This function returns DsEntry found after searching in the provided DsList.
Parameters
DsList is the Data Structure List in which the DS is searched
DsCnt is the number of Data Structures present in the List
DsHdr is the Data Structure Header to search for
Returns
XST_SUCCESS on success and error code on failure
Referenced by XPlmi_RestoreDataBackup().
u8 XPlmi_IsPlmUpdateDone (void)
This function checks if Inplace PLM update occurs or not.
Returns
TRUE if Inplace PLM Update and FALSE otherwise
References XPlmi_IsPlmUpdateDone().
Referenced by XPlmi_ClearSSSCfgErr(), XPlmi_EmInit(), XPlmi_GetPitResetValues(), XPlmi_IsPlmUpdateDone(), XPlmi_LpdInit(), XPlmi_PreInit(), XPlmi_PrintPlmBanner(), and XPlmi_RunTimeConfigInit().
u8 XPlmi_IsPlmUpdateInProgress (void)
This function checks if Inplace PLM update is in progress or not.
Returns
TRUE if Inplace PLM Update is in progress and FALSE otherwise
References XPlmi_IsPlmUpdateInProgress().
Referenced by XPlmi_IsPlmUpdateInProgress(), and XPlmi_PlmUpdate().
int XPlmi_PlmUpdate (XPlmi_Cmd * Cmd)
This function does In-Place PLM Update.
Parameters
Cmd is the command pointer of in place update command
Returns
XST_SUCCESS on success and error code on failure
References XPLMI_ERR_PLM_UPDATE_DISABLED, XPLMI_ERR_PLM_UPDATE_SHUTDOWN_INIT, XPLMI_ERR_UPDATE_IN_PROGRESS, XPLMI_ERR_UPDATE_TASK_NOT_FOUND, XPlmi_GetTaskInstance(), XPlmi_IsPlmUpdateInProgress(), and XPlmi_TaskTriggerNow().
Referenced by XPlmi_InPlacePlmUpdate().
int XPlmi_RestoreDataBackup (void)
This function restore all the data structures after InPlace PLM udpate.
Returns
XST_SUCCESS on success and error code on failure
References XPLMI_ERR_DB_ENDADDR_INVALID, XPLMI_ERR_DB_HDR_SIZE_MISMATCH, XPLMI_ERR_DB_HDR_VERSION_MISMATCH, XPLMI_ERR_INVALID_RESTORE_DS_HANDLER, XPLMI_ERR_PLM_UPDATE_NO_DS_FOUND, and XPlmi_GetDsEntry().