xilnvm: XilNvm eFUSE Versal Client APIs
XilNvm eFUSE Versal Client APIs
Macros
#define XNVM_SLR_INDEX_SHIFT (6U)
< Slr index shift constant
#define XNVM_SLR_INDEX_3 (3U)
PPK Read Offsets constants.
Functions
int XNvm_EfuseWrite (XNvm_ClientInstance *InstancePtr, const u64 DataAddr)
This function sends IPI request to program eFuses with user provided data.
int XNvm_EfuseWriteIVs (XNvm_ClientInstance *InstancePtr, const u64 IvAddr, const u32 EnvDisFlag)
This function sends IPI request to program IV eFuses with user provided data.
int XNvm_EfuseRevokePpk (XNvm_ClientInstance *InstancePtr, const XNvm_PpkType PpkRevoke, const u32 EnvDisFlag)
This function sends IPI request to program PPK_INVLD eFuse requested by the user.
int XNvm_EfuseWriteRevocationId (XNvm_ClientInstance *InstancePtr, const u32 RevokeId, const u32 EnvDisFlag)
This function sends IPI request to program revoke id eFuses requested by the user.
int XNvm_EfuseWriteUserFuses (XNvm_ClientInstance *InstancePtr, const u64 UserFuseAddr, const u32 EnvDisFlag)
This function sends IPI request to program User eFuses requested by the user.
int XNvm_EfuseReadIv (XNvm_ClientInstance *InstancePtr, const u64 IvAddr, const XNvm_IvType IvType)
This function sends IPI request to read IV eFuses requested by the user.
int XNvm_EfuseReadRevocationId (XNvm_ClientInstance *InstancePtr, const u64 RevokeIdAddr, const XNvm_RevocationId RevokeIdNum)
This function sends IPI request to read Revocation ID eFuses requested by the user.
int XNvm_EfuseReadUserFuses (XNvm_ClientInstance *InstancePtr, const u64 UserFuseAddr)
This function sends IPI request to read User eFuses requested by the user.
int XNvm_EfuseReadMiscCtrlBits (XNvm_ClientInstance *InstancePtr, const u64 MiscCtrlBits)
This function sends IPI request to read MiscCtrlBits requested by the user.
int XNvm_EfuseReadSecCtrlBits (XNvm_ClientInstance *InstancePtr, const u64 SecCtrlBits)
This function sends IPI request to read SecCtrlBits requested by the user.
int XNvm_EfuseReadSecMisc1Bits (XNvm_ClientInstance *InstancePtr, const u64 SecMisc1Bits)
This function sends IPI request to read SecMisc1Bits requested by the user.
int XNvm_EfuseReadBootEnvCtrlBits (XNvm_ClientInstance *InstancePtr, const u64 BootEnvCtrlBits)
This function sends IPI request to read BootEnvCtrlBits requested by the user.
int XNvm_EfuseReadPufSecCtrlBits (XNvm_ClientInstance *InstancePtr, const u64 PufSecCtrlBits)
This function sends IPI request to read PufSecCtrlBits requested by the user.
int XNvm_EfuseReadOffchipRevokeId (XNvm_ClientInstance *InstancePtr, const u64 OffChidIdAddr, const XNvm_OffchipId OffChipIdNum)
This function sends IPI request to read OffChip ID eFuses requested by the user.
int XNvm_EfuseReadPpkHash (XNvm_ClientInstance *InstancePtr, const u64 PpkHashAddr, const XNvm_PpkType PpkHashType)
This function sends IPI request to read PpkHash requested by the user.
int XNvm_EfuseReadDecOnly (XNvm_ClientInstance *InstancePtr, const u64 DecOnlyAddr)
This function sends IPI request to read DecEfuseOnly eFuses requested by the user.
int XNvm_EfuseReadDna (XNvm_ClientInstance *InstancePtr, const u64 DnaAddr)
This function sends IPI request to read DNA eFuses requested by the user.
int XNvm_EfuseWritePuf (XNvm_ClientInstance *InstancePtr, const u64 PufHdAddr)
This function sends IPI request to program Puf helper data requested by the user.
int XNvm_EfuseReadPuf (XNvm_ClientInstance *InstancePtr, const u64 PufHdAddr)
This function sends IPI request to read Puf helper data requested by the user.
Macro Definition Documentation
#define XNVM_SLR_INDEX_3 (3U)
PPK Read Offsets constants.
#define XNVM_SLR_INDEX_SHIFT (6U)
< Slr index shift constant
SlrIndexs constants
Function Documentation
int XNvm_EfuseReadBootEnvCtrlBits (XNvm_ClientInstance * InstancePtr, const u64 BootEnvCtrlBits)
This function sends IPI request to read BootEnvCtrlBits requested by the user.
Parameters
InstancePtr Pointer to the client instance
BootEnvCtrlBits Address of the output buffer to store the BootEnvCtrlBits eFuses data
Returns
- XST_SUCCESS - If the read is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to Read Boot Environment control bits from eFuse cache. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseReadDecOnly (XNvm_ClientInstance * InstancePtr, const u64 DecOnlyAddr)
This function sends IPI request to read DecEfuseOnly eFuses requested by the user.
Parameters
InstancePtr Pointer to the client instance
DecOnlyAddr Address of the output buffer to store the DecEfuseOnly eFuses data
Returns
- XST_SUCCESS - If the read is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to Read user specified decrypt eFuse only bits from eFuse cache. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseReadDna (XNvm_ClientInstance * InstancePtr, const u64 DnaAddr)
This function sends IPI request to read DNA eFuses requested by the user.
Parameters
InstancePtr Pointer to the client instance
DnaAddr Address of the output buffer to store the DNA eFuses data
Returns
- XST_SUCCESS - If the read is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to Read user specified eFuses DNA bits from eFuse cache. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseReadIv (XNvm_ClientInstance * InstancePtr, u64 IvAddr, const XNvm_IvType IvType)
This function sends IPI request to read IV eFuses requested by the user.
Parameters
InstancePtr Pointer to the client instance
IvAddr Address of the output buffer to store the IV eFuse data
IvType Type of the IV to read out
Returns
- XST_SUCCESS - If the read is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to Read user specified IV from eFuse cache. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseReadMiscCtrlBits (XNvm_ClientInstance * InstancePtr, const u64 MiscCtrlBits)
This function sends IPI request to read MiscCtrlBits requested by the user.
Parameters
InstancePtr Pointer to the client instance
MiscCtrlBits Address of the output buffer to store the MiscCtrlBits eFuses data
Returns
- XST_SUCCESS - If the read is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to Read miscellaneous control eFuses from eFuse cache. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseReadOffchipRevokeId (XNvm_ClientInstance * InstancePtr, const u64 OffChidIdAddr, const XNvm_OffchipId OffChipIdNum)
This function sends IPI request to read OffChip ID eFuses requested by the user.
Parameters
InstancePtr Pointer to the client instance
OffChipIdAddr Address of the output buffer to store the OffChip ID eFuse data
OffChipIdNum OffChip ID number to be read out
Returns
- XST_SUCCESS - If the read is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to Read user specified Offchip revoke registers from eFuse cache. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseReadPpkHash (XNvm_ClientInstance * InstancePtr, const u64 PpkHashAddr, const XNvm_PpkType PpkHashType)
This function sends IPI request to read PpkHash requested by the user.
Parameters
InstancePtr Pointer to the client instance
PpkHashAddr Address of the output buffer to store the PpkHashAddr eFuses data
PpkHashType Type of the PpkHash to be read out
Returns
- XST_SUCCESS - If the read is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to Read user specified PPK from eFuse cache. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseReadPuf (XNvm_ClientInstance * InstancePtr, const u64 PufHdAddr)
This function sends IPI request to read Puf helper data requested by the user.
Parameters
InstancePtr Pointer to the client instance
PufHdAddr Address of the output buffer to store the Puf helper data
Returns
- XST_SUCCESS - If the read is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to read user specified PUF helper data from eFuse cache. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseReadPufSecCtrlBits (XNvm_ClientInstance * InstancePtr, const u64 PufSecCtrlBits)
This function sends IPI request to read PufSecCtrlBits requested by the user.
Parameters
InstancePtr Pointer to the client instance
PufSecCtrlBits Address of the output buffer to store the PufSecCtrlBits eFuses data
Returns
- XST_SUCCESS - If the read is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to Read user specified Puf security control eFuses from eFuse cache. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseReadRevocationId (XNvm_ClientInstance * InstancePtr, const u64 RevokeIdAddr, const XNvm_RevocationId RevokeIdNum)
This function sends IPI request to read Revocation ID eFuses requested by the user.
Parameters
InstancePtr Pointer to the client instance
RevokeIdAddr Address of the output buffer to store the Revocation ID eFuse data
RevokeIdNum Revocation ID to be read out
Returns
- XST_SUCCESS - If the read is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to Read user specified Revocation ID from eFuse cache. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseReadSecCtrlBits (XNvm_ClientInstance * InstancePtr, const u64 SecCtrlBits)
This function sends IPI request to read SecCtrlBits requested by the user.
Parameters
InstancePtr Pointer to the client instance
SecCtrlBits Address of the output buffer to store the SecCtrlBits eFuses data
Returns
- XST_SUCCESS - If the read is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to Read security control eFuses from eFuse cache. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseReadSecMisc1Bits (XNvm_ClientInstance * InstancePtr, const u64 SecMisc1Bits)
This function sends IPI request to read SecMisc1Bits requested by the user.
Parameters
InstancePtr Pointer to the client instance
SecMisc1Bits Address of the output buffer to store the SecMisc1Bits eFuses data
Returns
- XST_SUCCESS - If the read is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to Read security and miscellaneous control eFuses from eFuse cache. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseReadUserFuses (XNvm_ClientInstance * InstancePtr, u64 UserFuseAddr)
This function sends IPI request to read User eFuses requested by the user.
Parameters
InstancePtr Pointer to the client instance
UserFuseAddr Address of the output buffer to store the User eFuse data
Returns
- XST_SUCCESS - If the read is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to Read user specified user eFuses from eFuse cache. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseRevokePpk (XNvm_ClientInstance * InstancePtr, const XNvm_PpkType PpkRevoke, const u32 EnvDisFlag)
This function sends IPI request to program PPK_INVLD eFuse requested by the user.
Parameters
InstancePtr Pointer to the client instance
PpkRevoke Type of PPK_INVLD to be revoked
EnvDisFlag Flag that tells whether to enable/disable Environmental monitoring in XilNvm
Returns
- XST_SUCCESS - If the programming is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Sends CDO to PLM to write eFuses to revoke the user specified PPK. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseWrite (XNvm_ClientInstance * InstancePtr, const u64 DataAddr)
This function sends IPI request to program eFuses with user provided data.
Parameters
InstancePtr Pointer to the client instance
DataAddr Address of the data structure where the eFUSE data to be programmed is stored
Returns
- XST_SUCCESS - If the eFUSE programming is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Sends EFUSE WRITE CDO to PLM through IPI. Return XST_FAILURE if IPI request of sending CDO not success.
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
Referenced by XNvm_EfuseRevokePpk(), XNvm_EfuseWriteIVs(), XNvm_EfuseWriteRevocationId(), and XNvm_EfuseWriteUserFuses().
int XNvm_EfuseWriteIVs (XNvm_ClientInstance * InstancePtr, const u64 IvAddr, const u32 EnvDisFlag)
This function sends IPI request to program IV eFuses with user provided data.
Parameters
InstancePtr Pointer to the client instance
IvAddr Address of the data structure where the eFUSE data to be programmed is stored
EnvDisFlag Flag that tells weather to enable/disable Environmental monitoring in XilNvm
Returns
- XST_SUCCESS - If the programming is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Link Shared memory for IPI usage. If shared memory is not assigned return XST_FAILURE
Clean the shared memory
Sends EFUSE WRITE IV CDO to PLM through IPI request. Return XST_FAILURE if IPI request is failed
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseWritePuf (XNvm_ClientInstance * InstancePtr, const u64 PufHdAddr)
This function sends IPI request to program Puf helper data requested by the user.
Parameters
InstancePtr Pointer to the client instance
PufHdAddr Address of the XNvm_EfusePufHdAddr structure where the user provided helper data to be programmed
Returns
- XST_SUCCESS - If the programming is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to write user specified PUF helper data to eFuses. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseWriteRevocationId (XNvm_ClientInstance * InstancePtr, const u32 RevokeId, const u32 EnvDisFlag)
This function sends IPI request to program revoke id eFuses requested by the user.
Parameters
InstancePtr Pointer to the client instance
RevokeId RevokeId number to be revoked
EnvDisFlag Flag that tells whether to enable/disable Environmental monitoring in XilNvm
Returns
- XST_SUCCESS - If the programming is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
send Revocation Id CDO to PLM to write to the user specified revocation eFuses. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.
int XNvm_EfuseWriteUserFuses (XNvm_ClientInstance * InstancePtr, const u64 UserFuseAddr, const u32 EnvDisFlag)
This function sends IPI request to program User eFuses requested by the user.
Parameters
InstancePtr Pointer to the client instance
UserFuseAddr Address of the XNvm_EfuseUserData structure where the user provided data to be programmed
EnvDisFlag Flag that tells whether to enable/disable Environmental monitoring in XilNvm
Returns
- XST_SUCCESS - If the programming is successful
XST_FAILURE - If there is a failure
Validate input parameters. Return XST_FAILURE if input parameters are invalid
Send CDO to PLM to write user specified user eFuses. Return XST_FAILURE if IPI request not success
References XNvm_ProcessMailbox(), and XNVM_SLR_INDEX_SHIFT.