xilnvm: XilNvm Versal eFuse APIs
XilNvm Versal eFuse APIs
Modules
XilNvm Versal Error Codes
Macros
#define XNVM_PUF_FORMATTED_SYN_DATA_LEN_IN_WORDS (127U)
< PUF syndrome length definations for Versal eFuse
#define XNVM_PUF_ROW_UPPER_NIBBLE_MASK (0xF0000000U)
User efuses start, end and number of efuses definations.
#define XNVM_NUM_OF_USER_FUSES (63U)
Maximum revoke id defination for versal.
#define XNVM_EFUSE_FULL_RANGE_TEMP_MIN (-55.0f)
Temaperature limits defination for versal Efuses.
#define XNVM_EFUSE_TEMP_HP_MAX (125.0f)
eFuse Range check definations
#define XNVM_EFUSE_HP_RANGE_CHECK (3U)
eFuse volatage limits definations
enum XNvm_SecCtrlBitColumns
eFuse control bits
int XNvm_EfuseWrite (const XNvm_EfuseData *WriteNvm)
This function is used as a wrapper to program below eFuses AES key User key 0 User key 1 PPK0/PPK1/PPK2/PPK3/PPK4 hash IVs Revocation Ids User Fuses Secure and Control bits.
int XNvm_EfuseWriteIVs (XNvm_EfuseIvs *EfuseIv, XSysMonPsv *SysMonInstPtr)
This function programs the eFUSEs with the IV.
int XNvm_EfuseRevokePpk (XNvm_PpkType PpkRevoke, XSysMonPsv *SysMonInstPtr)
This function revokes the Ppk.
int XNvm_EfuseWriteRevocationId (u32 RevokeId, XSysMonPsv *SysMonInstPtr)
This function writes Revocation eFuses.
int XNvm_EfuseWriteUserFuses (XNvm_EfuseUserData *WriteUserFuses, XSysMonPsv *SysMonInstPtr)
This function Programs User eFuses.
int XNvm_EfuseReadIv (XNvm_Iv *EfuseIv, XNvm_IvType IvType)
This function is used to read IV eFUSE bits from cache.
int XNvm_EfuseReadRevocationId (u32 *RevokeFusePtr, XNvm_RevocationId RevokeFuseNum)
This function reads the Revocation Fuse from eFUSE cache.
int XNvm_EfuseReadUserFuses (const XNvm_EfuseUserData *UserFusesData)
This function reads User eFuses from Cache.
int XNvm_EfuseReadMiscCtrlBits (XNvm_EfuseMiscCtrlBits *MiscCtrlBits)
This function is used to read the miscellaneous eFUSE control bits from cache.
int XNvm_EfuseReadSecCtrlBits (XNvm_EfuseSecCtrlBits *SecCtrlBits)
This function is used to read the eFUSE secure control bits from cache.
int XNvm_EfuseReadPpkHash (XNvm_PpkHash *EfusePpk, XNvm_PpkType PpkType)
This function reads the Ppk Hash from eFUSE cache.
int XNvm_EfuseReadDecOnly (u32 *DecOnly)
This function is used to read DecEfuseOnly eFUSE bits from cache.
int XNvm_EfuseReadDna (XNvm_Dna *EfuseDna)
This function is used to read Dna eFUSE bits from cache.
int XNvm_EfuseWritePuf (const XNvm_EfusePufHd *PufHelperData)
This function programs the eFUSEs with the PUF helper data.
int XNvm_EfuseReadPuf (XNvm_EfusePufHd *PufHelperData)
This function reads the PUF helper data from eFUSE cache.
int XNvm_EfuseReadPufSecCtrlBits (XNvm_EfusePufSecCtrlBits *PufSecCtrlBits)
This function is used to read the Puf eFUSE secure control bits from cache.
int XNvm_EfuseReadSecMisc1Bits (XNvm_EfuseSecMisc1Bits *SecMisc1Bits)
This function is used to read the security miscellaneous1 bits from cache.
int XNvm_EfuseReadBootEnvCtrlBits (XNvm_EfuseBootEnvCtrlBits *BootEnvCtrlBits)
This function reads the Boot Environmental Control bits from cache.
int XNvm_EfuseReadOffchipRevokeId (u32 *OffchipIdPtr, XNvm_OffchipId OffchipIdNum)
This function reads the Offchip revoke eFuse value from eFUSE cache.
Macro Definition Documentation
#define XNVM_EFUSE_FULL_RANGE_TEMP_MIN (-55.0f)
Temaperature limits defination for versal Efuses.
#define XNVM_EFUSE_HP_RANGE_CHECK (3U)
eFuse volatage limits definations
#define XNVM_EFUSE_TEMP_HP_MAX (125.0f)
eFuse Range check definations
#define XNVM_NUM_OF_USER_FUSES (63U)
Maximum revoke id defination for versal.
Referenced by XNvm_EfuseReadUserFuses().
#define XNVM_PUF_FORMATTED_SYN_DATA_LEN_IN_WORDS (127U)
< PUF syndrome length definations for Versal eFuse
#define XNVM_PUF_ROW_UPPER_NIBBLE_MASK (0xF0000000U)
User efuses start, end and number of efuses definations.
Enumeration Type Documentation
enum XNvm_SecCtrlBitColumns
eFuse control bits
< This structer defines Security control bits
Function Documentation
int XNvm_EfuseReadBootEnvCtrlBits (XNvm_EfuseBootEnvCtrlBits * BootEnvCtrlBits)
This function reads the Boot Environmental Control bits from cache.
Parameters
BootEnvCtrlBits - Pointer to the XNvm_EfuseBootEnvCtrlBits which holds the Boot Environmental control bits.
Returns
- XST_SUCCESS - On Successful read.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_CACHE_PARITY - Error while Cache reload.
Perform input parameter validation. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Read Directly from cache offset of BOOT_ENV_CTRL offset to fill the BootEnvCtrlBits structure. Return XST_SUCCESS if read is success
References XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_TEMP_EN_MASK, and XNVM_EFUSE_ERR_INVALID_PARAM.
int XNvm_EfuseReadDecOnly (u32 * DecOnly)
This function is used to read DecEfuseOnly eFUSE bits from cache.
Parameters
DecOnly - Pointer to the DecOnly efuse data.
Returns
- XST_SUCCESS - On Successful read.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_RD_DEC_ONLY - Error in reading in Dec_only efuses.
Note
If DecOnly eFuse is programmed that means boot can happen in only Symmetric HWRoT boot mode.
validate input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Read directly from cache offset of the DecOnly eFuse to fill the input param. Return XST_SUCCESS if read success
References XNVM_EFUSE_ERR_INVALID_PARAM, and XNVM_EFUSE_ERR_RD_DEC_ONLY.
int XNvm_EfuseReadDna (XNvm_Dna * EfuseDna)
This function is used to read Dna eFUSE bits from cache.
Parameters
EfuseDna - Pointer to the XNvm_Dna, which holds the read DNA.
Returns
- XST_SUCCESS - On Successful read.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid parameter.
XNVM_EFUSE_ERR_RD_DNA - Error in reading DNA efuses.
validate input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Read directly from cache offset of the Dna to fill the Dna array. Return XST_SUCCESS if read success
References XNVM_EFUSE_ERR_INVALID_PARAM, and XNVM_EFUSE_ERR_RD_DNA.
int XNvm_EfuseReadIv (XNvm_Iv * EfuseIv, XNvm_IvType IvType)
This function is used to read IV eFUSE bits from cache.
Parameters
EfuseIv - Pointer to the XNvm_Iv, which contains read IV data.
IvType - Iv to be read.
Returns
- XST_SUCCESS - On Successful read.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_RD_META_HEADER_IV - Error while reading MetaHeader IV.
XNVM_EFUSE_ERR_RD_BLACK_OBFUS_IV - Error while reading BlkObfus IV.
XNVM_EFUSE_ERR_RD_PLM_IV - Error while reading PLM IV.
XNVM_EFUSE_ERR_RD_DATA_PARTITION_IV - Error while reading Data Partition IV.
validate input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Based on user input IvType Reads the efuse cache. Fills EfuseIv structure. If read cache fails zeroize the EfuseIv data and return XST_FAILURE.
References XNVM_EFUSE_ERR_IN_ZEROIZATION, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_RD_BLACK_IV, XNVM_EFUSE_ERR_RD_DATA_PARTITION_IV_RANGE, XNVM_EFUSE_ERR_RD_META_HEADER_IV_RANGE, XNVM_EFUSE_ERR_RD_PLM_IV_RANGE, XNVM_EFUSE_META_HEADER_IV_START_ROW, and XNvm_ZeroizeAndVerify().
int XNvm_EfuseReadMiscCtrlBits (XNvm_EfuseMiscCtrlBits * MiscCtrlBits)
This function is used to read the miscellaneous eFUSE control bits from cache.
Parameters
MiscCtrlBits - Pointer to the XNvm_MiscCtrlBits which holds the read secure control bits.
Returns
- XST_SUCCESS - On Successful read.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_CACHE_PARITY - Error while Cache reload.
Validate input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Read directly from cache offset of the MiscCtrl to fill the MiscCtrlBits structure
References XNVM_EFUSE_CACHE_MISC_CTRL_GD_HALT_BOOT_EN_1_0_MASK, and XNVM_EFUSE_ERR_INVALID_PARAM.
int XNvm_EfuseReadOffchipRevokeId (u32 * OffchipIdPtr, XNvm_OffchipId OffchipIdNum)
This function reads the Offchip revoke eFuse value from eFUSE cache.
Parameters
OffchipIdPtr - Pointer to the data which hold the Offchip revoke ID values.
OffchipIdNum - Offchip fuse number to read.
Returns
- XST_SUCCESS - On successful read.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_CACHE_PARITY - Error in Cache reload.
validate input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Calculate offchip_revoke id offset based on which revoke id value is requested
Read directly from cache offset of the offchip revoke id offset to fill the OffchipIdPtr. Return XST_SUCCESS if the read is successful
References XNVM_EFUSE_ERR_INVALID_PARAM.
int XNvm_EfuseReadPpkHash (XNvm_PpkHash * EfusePpk, XNvm_PpkType PpkType)
This function reads the Ppk Hash from eFUSE cache.
Parameters
EfusePpk - Pointer to XNvm_PpkHash which holds the PpkHash from eFUSE Cache.
PpkType - Type of the Ppk to be programmed.
Returns
- XST_SUCCESS - On Successful read.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_RD_PPK_HASH - Error while reading PPK Hash.
validate input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Read directly from cache offset of the mentioned ppk type to fill the ppk hash array. Return XST_SUCCESS if read success
References XNVM_EFUSE_ERR_INVALID_PARAM, and XNVM_EFUSE_ERR_RD_PPK_HASH.
int XNvm_EfuseReadPuf (XNvm_EfusePufHd * PufHelperData)
This function reads the PUF helper data from eFUSE cache.
Parameters
PufHelperData - Pointer to XNvm_EfusePufHd which holds the PUF helper data read from eFUSEs.
Returns
- XST_SUCCESS - On successful read.
XNVM_EFUSE_ERR_RD_PUF_SYN_DATA - Error while reading SYN_DATA.
XNVM_EFUSE_ERR_RD_PUF_CHASH - Error while reading CHASH.
XNVM_EFUSE_ERR_RD_PUF_AUX - Error while reading AUX.
Validate input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Read directly from cache offset of the PUF syndrome data, Chash and Aux data to fill the PufHelperData structure. Return XST_SUCCESS if read is successful
References XNVM_EFUSE_ERR_IN_ZEROIZATION, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_RD_PUF_AUX, XNVM_EFUSE_ERR_RD_PUF_CHASH, XNVM_EFUSE_ERR_RD_PUF_SYN_DATA, XNVM_NUM_OF_ROWS_PER_PAGE, and XNvm_ZeroizeAndVerify().
int XNvm_EfuseReadPufSecCtrlBits (XNvm_EfusePufSecCtrlBits * PufSecCtrlBits)
This function is used to read the Puf eFUSE secure control bits from cache.
Parameters
PufSecCtrlBits - Pointer to the XNvm_PufSecCtrlBits, which holds the read secure control bits.
Returns
- XST_SUCCESS - On Successful read.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_CACHE_PARITY - Error while Cache reload.
Validate input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid.
Read directly from cache offset of the PUF_ECC_PUF_CTRL and also SEC_CRTL to fill the PufSecCtrlBits structure. Return XST_SUCESS if read is success.
References XNVM_EFUSE_ERR_INVALID_PARAM.
int XNvm_EfuseReadRevocationId (u32 * RevokeFusePtr, XNvm_RevocationId RevokeFuseNum)
This function reads the Revocation Fuse from eFUSE cache.
Parameters
RevokeFusePtr - Pointer to the data which hold the Revocation IDs from eFUSE Cache.
RevokeFuseNum - Revocation ID fuse number to read.
Returns
- XST_SUCCESS - On successful read.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_CACHE_PARITY - Error in Cache reload.
validate input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Read directly from cache offset of the Revocation Id to fill the Revocation Id array. Return XST_SUCCESS if the read is successful
References XNVM_EFUSE_ERR_INVALID_PARAM.
int XNvm_EfuseReadSecCtrlBits (XNvm_EfuseSecCtrlBits * SecCtrlBits)
This function is used to read the eFUSE secure control bits from cache.
Parameters
SecCtrlBits - Pointer to the Xnvm_SecCtrlBits which holds the read secure control bits.
Returns
- XST_SUCCESS - On Successful read.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_CACHE_PARITY - Error while Cache reload.
Perform input parameter validation. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Read Directly from cache offset of security control to fill the SecCtrlBits structure. Return XST_SUCCESS if read is success
References XNVM_EFUSE_ERR_INVALID_PARAM.
int XNvm_EfuseReadSecMisc1Bits (XNvm_EfuseSecMisc1Bits * SecMisc1Bits)
This function is used to read the security miscellaneous1 bits from cache.
Parameters
SecMisc1Bits - Pointer to the XNvm_EfuseSecMisc1Bits which holds the security miscellaneous1 control bits.
Returns
- XST_SUCCESS - On Successful read.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_CACHE_PARITY - Error while Cache reload.
Perform input parameter validation. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Read Directly from cache offset of SEC_MISC1 to fill SecMisc1Bits structure
References XNVM_EFUSE_CACHE_SEC_MISC_1_LPD_MBIST_EN_2_0_MASK, and XNVM_EFUSE_ERR_INVALID_PARAM.
int XNvm_EfuseReadUserFuses (const XNvm_EfuseUserData * UserFusesData)
This function reads User eFuses from Cache.
Parameters
UserFusesData - UserFuseData to be read from eFuse Cache.
Returns
- XST_SUCCESS - if reads successfully.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_RD_USER_FUSES - Error in reading User fuses.
validate input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Read directly from cache offset of the User Data eFuse to fill the UserFuseData address from specified UserFuse number (StartUserFuseNum) and number of eFuses to be read by NumOfUserFuses . Return XST_SUCCESS if the read is successful
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_RD_USER_FUSES, and XNVM_NUM_OF_USER_FUSES.
int XNvm_EfuseRevokePpk (XNvm_PpkType PpkRevoke, XSysMonPsv * SysMonInstPtr)
This function revokes the Ppk.
Parameters
PpkRevoke - Xnvm_RevokePpkFlags that tells which Ppk to revoke.
SysMonInstPtr - Pointer to the XSysMonPsv structure which contains XSysmonPsv driver instance data
Returns
- XST_SUCCESS - On Successful Revocation.
XNVM_EFUSE_ERR_LOCK - Error while Locking the controller.
validate input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Fill the XNvm_EfuseMiscCtrlBits structure with PPK INVLD inputs from user and fill the XNvm_EfuseData global structure with the MiscCtrlBits structure and call XNvm_EfuseWrite API. Return the Status.
References XNVM_EFUSE_ERR_INVALID_PARAM, and XNvm_EfuseWrite().
int XNvm_EfuseWrite (const XNvm_EfuseData * WriteNvm)
This function is used as a wrapper to program below eFuses AES key User key 0 User key 1 PPK0/PPK1/PPK2/PPK3/PPK4 hash IVs Revocation Ids User Fuses Secure and Control bits.
            Miscellaneous Control bits.
            Security Miscellaneous1 bits.
            BootEnvCtrl bits.
Parameters
WriteNvm - Pointer to Efuse data to be written.
Returns
- XST_SUCCESS - On Specified data write.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED - If nothing is programmed.
XNVM_EFUSE_ERR_BEFORE_PROGRAMMING - If error before programming.
XNVM_EFUSE_ERR_LOCK - Lock eFUSE Control Register.
Warning
After eFUSE programming is complete, the cache is automatically reloaded so all programmed eFUSE bits can be directly read from cache. If there is any CACHE_ERROR, user can reboot the system to reload the cache.
check for input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid.
Perform Environmental monitoring checks
Unlock Efuse controller
Validate all the write requests for AesKeys, PPK hash 0/1/2, Revocation Ids, Ivs, DecOnly, User eFuses, Glitch configuration, BootEnvCtrl, Misc1 Ctrl and offchip revocation eFuses
Reload the cache
Program the Protection Row Efuses
Reset Read mode
Disable Read mode
Lock Efuse controller
References XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNvm_EfuseDisableProgramming(), XNvm_EfuseLockController(), XNvm_EfuseResetReadMode(), and XNvm_EfuseSetupController().
int XNvm_EfuseWriteIVs (XNvm_EfuseIvs * EfuseIv, XSysMonPsv * SysMonInstPtr)
This function programs the eFUSEs with the IV.
Parameters
EfuseIv - Pointer to the XNvm_EfuseIvs, which contains IVs data to be written to the Efuse..
SysMonInstPtr - Pointer to the XSysMonPsv structure which contains XSysmonPsv driver instance data
Returns
- XST_SUCCESS - On Successful Write.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_WRITE_META_HEADER_IV - Error while writing MetaHeader Iv.
XNVM_EFUSE_ERR_WRITE_BLK_OBFUS_IV - Error while writing BlkObfus IV.
XNVM_EFUSE_ERR_WRITE_PLM IV - Error while writing PLM IV.
XNVM_EFUSE_ERR_WRITE_DATA_PARTITION_IV - Error while writing Data Partition IV.
validate Input parameters. Return XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED if input parameters are invalid
Fill the EfuseData structure with the IV address, Environmental disable flag and remaining as NULL
Fill the XNvm_EfuseData global structure with the EfuseIv structure and call XNvm_EfuseWrite API. Return the Status
References XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED, and XNvm_EfuseWrite().
int XNvm_EfuseWritePuf (const XNvm_EfusePufHd * PufHelperData)
This function programs the eFUSEs with the PUF helper data.
Parameters
PufHelperData - Pointer to the Puf helper data to be written to eFuse.
Returns
- XST_SUCCESS - if programs successfully.
XNVM_EFUSE_ERR_RD_PUF_SEC_CTRL - Error while reading PufSecCtrl.
XNVM_EFUSE_ERR_WRITE_PUF_HELPER_DATA - Error while writing Puf helper data.
XNVM_EFUSE_ERR_WRITE_PUF_SYN_DATA - Error while writing Puf Syndata.
XNVM_EFUSE_ERR_WRITE_PUF_CHASH - Error while writing Puf Chash.
XNVM_EFUSE_ERR_WRITE_PUF_AUX - Error while writing Puf Aux.
Note
To generate PufSyndromeData please use XPuf_Registration API.
Validate Input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Read driectly from cache offset of Puf SecCtrl bits
Check Environmental monitoring checks for temperature and voltage
Unlock Efuse controller
Set eFuse controller parameters for efuse write operation
Programming Puf Security control bits
Reload the cache once the programming of all the efuses requested are programmed
Program Corresponding Protection Row eFuses
Reset Read mode
Disable eFuse Programming mode
Lock eFuse controller
References XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_FUSE_PROTECTED, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_WRITE_PUF_AUX, XNVM_EFUSE_ERR_WRITE_PUF_CHASH, XNVM_EFUSE_ERR_WRITE_PUF_HELPER_DATA, XNVM_EFUSE_ERR_WRITE_PUF_SYN_DATA, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET, XNvm_EfuseDisableProgramming(), XNvm_EfuseLockController(), XNvm_EfuseResetReadMode(), and XNvm_EfuseSetupController().
int XNvm_EfuseWriteRevocationId (u32 RevokeId, XSysMonPsv * SysMonInstPtr)
This function writes Revocation eFuses.
Parameters
RevokeId - RevokeId number to program Revocation Id eFuses.
SysMonInstPtr - Pointer to the XSysMonPsv structure which contains XSysmonPsv driver instance data
Returns
- XST_SUCCESS - On successful write to eFuse.
XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
XNVM_EFUSE_ERR_LOCK - Error while Locking the controller.
Note
Example: If the revoke id to program is 64, it will program the 0th bit of the REVOCATION_ID_2 eFuse row.
validate input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Calculate the REVOCATION_ID eFuse row and the column based on the input provided
Fill the XNvm_EfuseRevokeIds structure with the calculated inputs and fill the XNvm_EfuseData global structure with the XNvm_EfuseRevokeIds and call XNvm_EfuseWrite API. Return the Status.
References XNVM_EFUSE_ERR_INVALID_PARAM, and XNvm_EfuseWrite().
int XNvm_EfuseWriteUserFuses (XNvm_EfuseUserData * WriteUserFuses, XSysMonPsv * SysMonInstPtr)
This function Programs User eFuses.
Parameters
WriteUserFuses - Pointer to the XNvm_EfuseUserData structure.
SysMonInstPtr - Pointer to the XSysMonPsv structure which contains XSysmonPsv driver instance data
Returns
- XST_SUCCESS - if programming is successful.
XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED - if NULL request is sent.
validate input parameters. Return XNVM_EFUSE_ERR_INVALID_PARAM if input parameters are invalid
Fill the XNvm_EfuseData global structure with the user provided WriteUserFuses and call XNvm_EfuseWrite API. Return the XST_SUCCESS
References XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED, and XNvm_EfuseWrite().