xilloader: xloader_plat.c File Reference
net/xloader_plat.c File Reference
Overview
This file contains the versal_net specific code related to PDI image loading.
MODIFICATION HISTORY:
Ver   Who  Date        Changes
----- ---- --------   -------------------------------------------------------
1.00  bm   07/06/2022 Initial release
      bm   07/13/2022 Retain critical data structures after In-Place PLM Update
      bm   07/18/2022 Shutdown modules gracefully during update
      dc   07/20/2022 Added support for data measurement
      dc   09/04/2022 Initialized TRNG
      is   09/12/2022 Remove PM_CAP_SECURE capability when requesting PSM_PROC,
                      TCM memory banks
1.01  ng   11/11/2022 Updated doxygen comments
      dc   12/27/2022 Added SHA1 instance
      kal  01/05/2023 Added PCR Extend functions for secure images
Note
Functions
XLoader_ImageInfoTbl * XLoader_GetImageInfoTbl (void)
This function provides ImageInfoTbl pointer.
XilPdi * XLoader_GetPdiInstance (void)
This function provides PdiInstance pointer.
XLoader_ImageStore * XLoader_GetPdiList (void)
This function provides pointer to PdiList.
XilPdi_ATFHandoffParams * XLoader_GetATFHandoffParamsAddr (void)
This function returns the ATFHandoffParams structure address to the caller.
int XLoader_StartImage (XilPdi *PdiPtr)
This function is used to start the subsystems in the PDI.
void XLoader_SetATFHandoffParameters (const XilPdi_PrtnHdr *PrtnHdr)
This function sets the handoff parameters to the ARM Trusted Firmware(ATF).
int XLoader_GetSDPdiSrcNAddr (u32 SecBootMode, XilPdi *PdiPtr, u32 *PdiSrc, u64 *PdiAddr)
This function is used to get PdiSrc and PdiAddr for Secondary SD boot modes.
int XLoader_ProcessElf (XilPdi *PdiPtr, const XilPdi_PrtnHdr *PrtnHdr, XLoader_PrtnParams *PrtnParams, XLoader_SecureParams *SecureParams)
This function copies the elf partitions to specified destinations.
int XLoader_UpdateHandoffParam (XilPdi *PdiPtr)
This function is used to update the handoff parameters.
int XLoader_ProcessDeferredError (void)
This function checks if MJTAG workaround is required.
int XLoader_UpdateHandler (XPlmi_ModuleOp Op)
This function provides update handler for xilloader.
int XLoader_PlatInit (void)
This function initializes the loader with platform specific initializations.
int XLoader_HdrMeasurement (XilPdi *PdiPtr)
This function measures the PDI's meta header data by calculating the hash using SHA3.
int XLoader_DataMeasurement (XLoader_ImageMeasureInfo *ImageInfo)
This function measures the data by calculating SHA3 hash.
int XLoader_SecureConfigMeasurement (XLoader_SecureParams *SecurePtr, u32 PcrInfo)
This function measures the Secure Configuration that is SPK, SPK ID and Encryption Revoke ID and extends to the specified PCR.
Function Documentation
int XLoader_DataMeasurement (XLoader_ImageMeasureInfo * ImageInfo)
This function measures the data by calculating SHA3 hash.
Parameters
ImageInfo Pointer to the XLoader_ImageMeasureInfo structure.
Returns
XST_SUCCESS on success and error code on failure
References XLoader_DataMeasurement().
Referenced by XLoader_DataMeasurement(), XLoader_HdrMeasurement(), and XLoader_PrtnCopy().
XilPdi_ATFHandoffParams* XLoader_GetATFHandoffParamsAddr (void)
This function returns the ATFHandoffParams structure address to the caller.
Returns
Returns ATFHandoffParams structure address
< Instance containing ATF handoff params
XLoader_ImageInfoTbl* XLoader_GetImageInfoTbl (void)
This function provides ImageInfoTbl pointer.
Returns
Pointer to ImageInfoTbl
XilPdi* XLoader_GetPdiInstance (void)
This function provides PdiInstance pointer.
Returns
Pointer to PdiInstance
XLoader_ImageStore* XLoader_GetPdiList (void)
This function provides pointer to PdiList.
Returns
pointer to PdiList
int XLoader_GetSDPdiSrcNAddr (u32 SecBootMode, XilPdi * PdiPtr, u32 * PdiSrc, u64 * PdiAddr)
This function is used to get PdiSrc and PdiAddr for Secondary SD boot modes.
Parameters
SecBootMode is the secondary boot mode value
PdiSrc is pointer to the source of PDI
PdiAddr is the pointer to the address of the Pdi
Returns
XST_SUCCESS on success and error code on failure
Get the PDI source address for the secondary boot device.
int XLoader_HdrMeasurement (XilPdi * PdiPtr)
This function measures the PDI's meta header data by calculating the hash using SHA3.
Parameters
PdiPtr is the pointer to PDI instance
Returns
XST_SUCCESS on success and error code on failure
References XLoader_DataMeasurement(), and XLoader_HdrMeasurement().
Referenced by XLoader_HdrMeasurement().
int XLoader_PlatInit (void)
This function initializes the loader with platform specific initializations.
Returns
XST_SUCCESS on success and error code on failure
References XLoader_PlatInit().
Referenced by XLoader_Init(), and XLoader_PlatInit().
int XLoader_ProcessDeferredError (void)
This function checks if MJTAG workaround is required.
Returns
Error Code of Deferred Error
int XLoader_ProcessElf (XilPdi * PdiPtr, const XilPdi_PrtnHdr * PrtnHdr, XLoader_PrtnParams * PrtnParams, XLoader_SecureParams * SecureParams)
This function copies the elf partitions to specified destinations.
Parameters
PdiPtr is pointer to XilPdi instance
PrtnHdr is pointer to the partition header
PrtnParams is pointer to the structure variable that contains parameters required to process the partition
SecureParams is pointer to the instance containing security related params
Returns
XST_SUCCESS on success and error code on failure
References XLoader_PrtnCopy(), XLoader_SetATFHandoffParameters(), and XLoader_UpdateHandoffParam().
int XLoader_SecureConfigMeasurement (XLoader_SecureParams * SecurePtr, u32 PcrInfo)
This function measures the Secure Configuration that is SPK, SPK ID and Encryption Revoke ID and extends to the specified PCR.
Parameters
SecurePtr is pointer to the XLoader_SecureParams instance.
PcrInfo provides the PCR number and Measurement Index to be extended.
Returns
XST_SUCCESS on success and error code on failure
References XLoader_SecureConfigMeasurement().
Referenced by XLoader_SecureConfigMeasurement().
void XLoader_SetATFHandoffParameters (const XilPdi_PrtnHdr * PrtnHdr)
This function sets the handoff parameters to the ARM Trusted Firmware(ATF).
Some of the inputs for this are taken from image partition header. A pointer to the structure containing these parameters is stored in the PMC_GLOBAL.GLOBAL_GEN_STORAGE4 register, which ATF reads.
Parameters
PrtnHdr is pointer to Partition header details
Returns
None
Read partition header and deduce entry point and partition flags.
Update CPU number based on destination CPU
References XLoader_GetATFHandoffParamsAddr().
int XLoader_StartImage (XilPdi * PdiPtr)
This function is used to start the subsystems in the PDI.
Parameters
PdiPtr Pdi instance pointer
Returns
XST_SUCCESS on success and error code on failure
Start Handoff to the cpus
Wake up each processor
Make Number of handoff CPUs to zero
int XLoader_UpdateHandler (XPlmi_ModuleOp Op)
This function provides update handler for xilloader.
Parameters
Op is the module operation variable
Returns
XST_SUCCESS on success and error code on failure
References XLoader_CheckAuthJtagIntStatus(), and XLoader_CheckDeviceStateChange().
int XLoader_UpdateHandoffParam (XilPdi * PdiPtr)
This function is used to update the handoff parameters.
Parameters
PdiPtr is pointer to XilPdi instance
Returns
XST_SUCCESS on success and error code on failure