xilloader: xloader_auth_enc.c File Reference
xloader_auth_enc.c File Reference
Overview
This file contains authentication and encryption related code.
MODIFICATION HISTORY:
Ver   Who  Date     Changes
----- ---- -------- -------------------------------------------------------
1.00  bm   12/16/20 First release
      kal  12/23/20 Initialize Status to XST_FAILURE in XLoader_AesKatTest
      kpt  01/06/21 Added redundancy for the loop in XLoader_CheckNonZeroPpk
      kpt  01/12/21 Added check to validate keysrc for partitions when
                    DEC only efuse bits are set
      kpt  01/18/21 Added check to validate the index of for loop with lower
                    bounds of ppk offset in XLoader_CheckNonZeroPpk
      har  01/19/21 Added support for P521 KAT
      kpt  01/21/21 Added check to verify revoke id before enabling Auth Jtag
      har  02/01/21 Added check for metaheader encryption source
      bm   02/12/21 Updated logic to use BootHdr directly from PMC RAM
      kpt  02/16/21 Corrected check to return valid error code in case of
                    MetaHeader IV mismatch and fixed gcc warning
      har  03/02/21 Added support to verify IHT as AAD for first secure header
      har  03/17/21 Cleaned up code to use the secure state of boot
      ma   03/24/21 Redirect XilPdi prints to XilLoader
      ma   03/24/21 Minor updates to prints in XilLoader
      bm   04/10/21 Updated scheduler function calls
      kpt  04/14/21 Added check to verify whether the encrypted data is 128 bit
                    aligned
      bm   05/10/21 Updated chunking logic for hashes
      bm   05/13/21 Updated code to use common crypto instances from xilsecure
      ma   05/18/21 Minor code cleanup
      har  05/19/21 Support decryption of partition even if Secure state of
                    boot is A-HWRoT or Emulated A-HWRoT
      ma   05/21/21 Read KAT Status from RTCA Secure Boot State location
1.01  kpt  06/23/21 Added check to compare DNA before enabling Auth Jtag
           07/01/21 Added support to disable Jtag as per the timeout
                    set by user
      td   07/08/21 Fix doxygen warnings
      ma   07/12/21 Register NULL error handler for
                    XLoader_CheckAuthJtagIntStatus scheduler task
      har  07/15/21 Fixed doxygen warnings
      td   07/15/21 Fixed doxygen warnings
      bsv  08/17/21 Code clean up
      rb   08/11/21 Fix compilation warnings
      bm   08/24/2021 Added Extract Metaheader support
      bsv  08/31/21 Code clean up
      kpt  09/02/21 Added support to update KAT status in RTC area
      am   09/09/21 Fixed multiple SPK Authentication while authenticating
                    MetaHeader
      kpt  09/09/21 Fixed SW-BP-BLIND-WRITE in XLoader_AuthEncClear
      kpt  09/15/21 Modified check for PUF HD in XLoader_SecureEncOnlyValidations
      kpt  09/18/21 Fixed SW-BP-REDUNDANCY
                    Added check in XLoader_CheckAuthJtagIntStatus to avoid access
                    to auth jtag if there is a failure in single attempt
                    Renamed BHSignature variable to IHTSignature
      bsv  10/01/21 Addressed code review comments
1.02  kpt  10/01/21 Removed redundant code in XLoader_VerifyRevokeId
      kpt  10/07/21 Decoupled checksum functionality from secure code
      kpt  10/20/21 Modified temporal checks to use temporal variables from
                    data section
      kpt  10/28/21 Fixed PMCDMA1 hang issue in sbi checksum copy to memory
                    mode
1.03  skd  11/18/21 Added time stamps in XLoader_ProcessAuthEncPrtn
      bsv  12/04/21 Address security review comment
      kpt  12/13/21 Replaced standard library utility functions with xilinx
                    maintained functions
      skd  01/11/22 Moved comments to its proper place
      skd  01/12/22 Updated goto labels for better readability
      bsv  02/09/22 Code clean up to reduce stack size
      bsv  02/09/22 Code clean up
      bsv  02/10/22 Code clean up by removing unwanted initializations
      bsv  02/11/22 Code optimization to reduce text size
      bsv  02/13/22 Reduce stack usage of functions
      har  02/17/22 Updated code to limit number of attempts to enable JTAG
                    when efuse bits are set
1.04  skg  06/20/22 Fixed MISRA C Rule 10.3 violation
      bm   07/06/22 Refactor versal and versal_net code
      kpt  07/07/22 Added support to update KAT status
      bsv  07/08/22 Changes related to Optional data in Image header table
      kpt  07/24/22 Added support to go into secure lockdown when KAT fails
      kpt  08/03/22 Added volatile keyword to avoid compiler optimization
                    of loop redundancy checks
1.05  har  10/11/22 Used temporal check macro for redundancy checks for Xil_SMemCpy
      sk   10/19/22 Fix security review comments
      har  11/17/22 Made XLoader_CheckNonZeroPpk as non-static and moved here from xloader_secure.c file
      ng   11/23/22 Updated doxygen comments
1.8   skg  12/07/22 Added Additional PPKs support
      kal  01/05/23 Moved XLoader_GetAuthPubAlgo function to header file
      sk   02/08/23 Renamed XLoader_UpdateKatStatus to XLoader_ClearKatOnPPDI
      sk   02/09/23 Fixed Sec Review comments in XLoader_RsaSignVerify function
Note
Macros
#define XLOADER_RSA_PSS_MSB_PADDING_MASK (u8)(0x80U)
RSA PSS MSB padding mask.
#define XLOADER_RSA_EM_MSB_INDEX (0x0U)
RSA EM MSB Index.
#define XLOADER_PUF_SHUT_GLB_VAR_FLTR_EN_SHIFT (31U)
Shift for Global Variation Filter in PUF shutter value.
#define XLOADER_AES_KEY_CLR_REG (0xF11E0014U)
AES key clear register address.
#define XLOADER_AES_ALL_KEYS_CLR_VAL (0x3FFFF3U)
AES all key clear value.
#define XLOADER_AES_KEY_ZEROED_STATUS_REG (0xF11E0064U)
AES key zeroed register address.
#define XLOADER_AES_RESET_VAL (0x1U)
AES Reset value.
#define XLOADER_AES_RESET_REG (0xF11E0010U)
AES Reset register address.
#define XLOADER_ECDSA_RSA_RESET_REG (0xF1200040U)
ECDSA RSA Reset register address.
#define XLOADER_ECDSA_RSA_RESET_VAL (0x1U)
ECDSA RSA Reset value.
Functions
int XLoader_SecureAuthInit (XLoader_SecureParams *SecurePtr, const XilPdi_PrtnHdr *PrtnHdr)
This function initializes authentication parameters of XLoader_SecureParams's instance.
int XLoader_SecureEncInit (XLoader_SecureParams *SecurePtr, const XilPdi_PrtnHdr *PrtnHdr)
This function initializes encryption parameters of XLoader_SecureParams's instance.
int XLoader_SecureValidations (const XLoader_SecureParams *SecurePtr)
This function checks if authentication/encryption is compulsory.
int XLoader_ImgHdrTblAuth (XLoader_SecureParams *SecurePtr)
This function authenticates the image header table.
int XLoader_ReadAndVerifySecureHdrs (XLoader_SecureParams *SecurePtr, XilPdi_MetaHdr *MetaHdr)
This function authenticates and/or decrypts the image headers and partition headers and copies the contents to the corresponding structures.
int XLoader_IsPpkValid (XLoader_PpkSel PpkSelect, const u8 *PpkHash)
The function reads PPK invalid bits.
int XLoader_RsaPssSignVerify (XPmcDma *PmcDmaInstPtr, u8 *MsgHash, XSecure_Rsa *RsaInstPtr, u8 *Signature)
This function encrypts the RSA signature provided and performs required PSS operations to extract salt and calculates M prime hash and compares with hash obtained from EM.
int XLoader_AddAuthJtagToScheduler (void)
This function adds periodic checks of the status of Auth JTAG interrupt status to the scheduler.
int XLoader_CheckAuthJtagIntStatus (void *Arg)
This function checks the status of Auth JTAG interrupt status and it disables the Jtag as per the timeout set by user.
int XLoader_AuthEncClear (void)
This function is called to clear secure critical data related to authentication and encryption in case of exceptions.
void XLoader_ClearKatOnPPDI (XLoader_SecureParams *SecurePtr, u32 PlmKatMask)
This function updates the KAT status.
int XLoader_ProcessAuthEncPrtn (XLoader_SecureParams *SecurePtr, u64 DestAddr, u32 BlockSize, u8 Last)
This function performs authentication and decryption of the partition.
Macro Definition Documentation
#define XLOADER_AES_ALL_KEYS_CLR_VAL (0x3FFFF3U)
AES all key clear value.
Referenced by XLoader_AuthEncClear().
#define XLOADER_AES_KEY_CLR_REG (0xF11E0014U)
AES key clear register address.
Referenced by XLoader_AuthEncClear().
#define XLOADER_AES_KEY_ZEROED_STATUS_REG (0xF11E0064U)
AES key zeroed register address.
Referenced by XLoader_AuthEncClear().
#define XLOADER_AES_RESET_REG (0xF11E0010U)
AES Reset register address.
Referenced by XLoader_AuthEncClear().
#define XLOADER_AES_RESET_VAL (0x1U)
AES Reset value.
Referenced by XLoader_AuthEncClear().
#define XLOADER_ECDSA_RSA_RESET_REG (0xF1200040U)
ECDSA RSA Reset register address.
Referenced by XLoader_AuthEncClear().
#define XLOADER_ECDSA_RSA_RESET_VAL (0x1U)
ECDSA RSA Reset value.
Referenced by XLoader_AuthEncClear().
#define XLOADER_PUF_SHUT_GLB_VAR_FLTR_EN_SHIFT (31U)
Shift for Global Variation Filter in PUF shutter value.
#define XLOADER_RSA_EM_MSB_INDEX (0x0U)
RSA EM MSB Index.
Referenced by XLoader_RsaPssSignVerify().
#define XLOADER_RSA_PSS_MSB_PADDING_MASK (u8)(0x80U)
RSA PSS MSB padding mask.
Referenced by XLoader_RsaPssSignVerify().
Function Documentation
int XLoader_AddAuthJtagToScheduler (void)
This function adds periodic checks of the status of Auth JTAG interrupt status to the scheduler.
Returns
XST_SUCCESS otherwise error code is returned
Read auth_jtag_disable efuse bits(20:19) of Security Control register in Efuse Cache module.
Read PPK hash registers in Efuse Cache module and check if they are non-zero.
Check the preconditions for adding task to the scheduler
Auth jtag disable efuse bits should not be set.
PPK hash registers should be non zero.
If the preconditions are correct then add task to the scheduler for calling the API to check Auth JTAG interrupt status.
The task should not be added to the scheduler if Auth JTAG disable efuse bit is set or PPK hash is not programmed in efuse. Thus forcing the Status to be XST_SUCCESS.
References XLOADER_AUTH_JTAG_DIS_MASK, XLoader_CheckAuthJtagIntStatus(), XLOADER_EFUSE_CACHE_SECURITY_CONTROL_OFFSET, and XLoader_GetAHWRoT().
Referenced by XLoader_Init().
int XLoader_AuthEncClear (void)
This function is called to clear secure critical data related to authentication and encryption in case of exceptions.
The function also places AES, ECDSA_RSA in reset.
Returns
XST_SUCCESS on success XST_FAILURE on failure
Clear AES keys if AES is out of reset
Place AES in reset
Clear Rsa memory
Place ECDSA RSA in reset
References XLOADER_AES_ALL_KEYS_CLR_VAL, XLOADER_AES_KEY_CLR_REG, XLOADER_AES_KEY_ZEROED_STATUS_REG, XLOADER_AES_RESET_REG, XLOADER_AES_RESET_VAL, XLOADER_ECDSA_RSA_RESET_REG, and XLOADER_ECDSA_RSA_RESET_VAL.
Referenced by XLoader_SecureClear().
int XLoader_CheckAuthJtagIntStatus (void * Arg)
This function checks the status of Auth JTAG interrupt status and it disables the Jtag as per the timeout set by user.
Parameters
Arg Not used in the function currently
Returns
XST_SUCCESS otherwise error code shall be returned
Note
If Auth JTAG interrupt status is set, then XLoader_AuthJtag API will be called.
Read Auth Jtag Interrupt Status register in PMC TAP module.
Check if Auth JTAG Lock disable efuse bits are set. If set then allow limited number of attempts to enable JTAG
References XLOADER_AUTH_JTAG_LOCK_DIS_MASK, XLOADER_AUTH_JTAG_MAX_ATTEMPTS, XLOADER_DAP_TIMEOUT_DISABLED, XLOADER_EFUSE_CACHE_SECURITY_CONTROL_OFFSET, XLOADER_PMC_TAP_AUTH_JTAG_INT_STATUS_MASK, and XLOADER_PMC_TAP_AUTH_JTAG_INT_STATUS_OFFSET.
Referenced by XLoader_AddAuthJtagToScheduler(), and XLoader_UpdateHandler().
void XLoader_ClearKatOnPPDI (XLoader_SecureParams * SecurePtr, u32 PlmKatMask)
This function updates the KAT status.
Parameters
SecurePtr is pointer to the XLoader_SecureParams instance
PlmKatMask is the mask of the KAT that is going to run
Returns
None
int XLoader_ImgHdrTblAuth (XLoader_SecureParams * SecurePtr)
This function authenticates the image header table.
Parameters
SecurePtr is pointer to the XLoader_SecureParams instance
Returns
XST_SUCCESS on success and error code on failure
Get DMA instance
Copy Authentication certificate from PDI to PMCRAM
Calculate SHA-3 hash of the image header table
Authenticate Image header table
References XLOADER_AUTH_CERT_MIN_SIZE.
int XLoader_IsPpkValid (XLoader_PpkSel PpkSelect, const u8 * PpkHash)
The function reads PPK invalid bits.
If the bits are valid, it compares the provided hash value with the programed hash value. Efuse stores only 256 bits of hash.
Parameters
PpkSelect PPK selection of eFUSE.
PpkHash Pointer to the PPK hash to be verified.
Returns
XST_SUCCESS on success and error code on failure
Check if PPK bits are valid or not by reading the EFUSE bits
Check if valid PPK hash is all zeros
References XLoader_AdditionalPpkSelect(), XLOADER_EFUSE_MISC_CTRL_OFFSET, XLOADER_EFUSE_MISC_CTRL_PPK0_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK1_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK2_INVLD, XLOADER_EFUSE_PPK0_START_OFFSET, XLOADER_EFUSE_PPK1_START_OFFSET, XLOADER_EFUSE_PPK2_START_OFFSET, XLOADER_EFUSE_PPK_HASH_LEN, XLOADER_PPK_SEL_0, XLOADER_PPK_SEL_1, XLOADER_PPK_SEL_2, XLOADER_SEC_PPK_HASH_ALLZERO_INVLD, and XLOADER_SEC_PPK_INVALID_BIT_ERR.
Referenced by XLoader_IsAdditionalPpkValid().
int XLoader_ProcessAuthEncPrtn (XLoader_SecureParams * SecurePtr, u64 DestAddr, u32 BlockSize, u8 Last)
This function performs authentication and decryption of the partition.
Parameters
SecurePtr is pointer to the XLoader_SecureParams instance
DestAddr is the address to which data is copied
BlockSize is size of the data block to be processed which doesn't include padding lengths and hash
Last notifies if the block to be processed is last or not
Returns
XST_SUCCESS on success and error code on failure
Process the 1st block
Verify encrypted partition is revoked or not
Verify hash
If encryption is enabled
Decrypt the data
References XLoader_GetTempParams(), XLOADER_SECURE_HDR_TOTAL_SIZE, and XLoader_SecureChunkCopy().
Referenced by XLoader_SecureAuthInit(), and XLoader_SecureEncInit().
int XLoader_ReadAndVerifySecureHdrs (XLoader_SecureParams * SecurePtr, XilPdi_MetaHdr * MetaHdr)
This function authenticates and/or decrypts the image headers and partition headers and copies the contents to the corresponding structures.
Parameters
SecurePtr Pointer to the XLoader_SecureParams instance.
MetaHdr Pointer to the Meta header table.
Returns
XST_SUCCESS on success and error code on failure
If headers are in encrypted format either authentication is enabled or not
Initialize AES driver
Validate Meta header length
Read headers to a buffer
Read IHT and PHT to buffers along with encryption overhead
Authenticate headers and decrypt the headers
Decrypt the headers
Read IHT and PHT to structures and verify checksum
Verify Meta header is revoked or not
Update buffer address to point to PHs
Authenticate Image headers and partition headers
References XLOADER_AUTH_CERT_MIN_SIZE, and XLoader_GetTempParams().
int XLoader_RsaPssSignVerify (XPmcDma * PmcDmaInstPtr, u8 * MsgHash, XSecure_Rsa * RsaInstPtr, u8 * Signature)
This function encrypts the RSA signature provided and performs required PSS operations to extract salt and calculates M prime hash and compares with hash obtained from EM.
Parameters
PmcDmaInstPtr Pointer to DMA instance
MsgHash of the data to be authenticated.
RsaInstPtr is pointer to the XSecure_Rsa instance.
Signature is pointer to RSA signature for data to be authenticated.
Returns
XST_SUCCESS on success and error code on failure
Initialise Buffer variable to store HashMgf and DB
RSA signature encryption with public key components
Check for signature encrypted message
Extract Salt and Generate DB from masked DB and Hash
XOR MGF output with masked DB from EM to get DB
Check DB = PS <414 zeros> || 0x01
Hash on M prime
Compare MPrime Hash with Hash from EM
References XLOADER_PARTITION_SIG_SIZE, XLOADER_RSA_EM_MSB_INDEX, XLOADER_RSA_PSS_MSB_PADDING_MASK, XLOADER_RSA_SIG_EXP_BYTE, XLOADER_SEC_EFUSE_DB_PATTERN_MISMATCH_ERROR, XLOADER_SEC_MASKED_DB_MSB_ERROR, XLOADER_SEC_MEMSET_ERROR, XLOADER_SEC_RSA_MEMSET_SHA3_ARRAY_FAIL, XLOADER_SEC_RSA_MEMSET_VARSCOM_FAIL, XLOADER_SEC_RSA_PSS_ENC_BC_VALUE_NOT_MATCHED, XLOADER_SEC_RSA_PSS_HASH_COMPARE_FAILURE, and XLOADER_SEC_RSA_PSS_SIGN_VERIFY_FAIL.
int XLoader_SecureAuthInit (XLoader_SecureParams * SecurePtr, const XilPdi_PrtnHdr * PrtnHdr)
This function initializes authentication parameters of XLoader_SecureParams's instance.
Parameters
SecurePtr is pointer to the XLoader_SecureParams instance
PrtnHdr is pointer to XilPdi_PrtnHdr instance that has to be processed
Returns
XST_SUCCESS on success and error code on failure
Check if authentication is enabled and copy authentication certificate from PDI source to memory location provided in image header.
References XLOADER_AUTH_CERT_MIN_SIZE, XLoader_GetTempParams(), and XLoader_ProcessAuthEncPrtn().
Referenced by XLoader_SecureInit().
int XLoader_SecureEncInit (XLoader_SecureParams * SecurePtr, const XilPdi_PrtnHdr * PrtnHdr)
This function initializes encryption parameters of XLoader_SecureParams's instance.
Parameters
SecurePtr is pointer to the XLoader_SecureParams instance
PrtnHdr is pointer to XilPdi_PrtnHdr instance that has to be processed
Returns
XST_SUCCESS on success and error code on failure
Check if encryption is enabled
Error out if checksum is enabled along with authentication or encryption.
Run AES Kat test if the image is encrypted and metaheader is not encrypted
Check secure state of boot as partition is allowed to be encrypted only if Secure state of boot is S-HWRoT, Emul S-HWRoT, A-HWRoT or Emul A-HWRoT.
Check Secure State of the device. If S-HWRoT is enabled, then validate keysrc
References XLOADER_BBRAM_KEY, XLOADER_EFUSE_KEY, XLoader_GetAHWRoT(), XLoader_GetSHWRoT(), XLoader_GetTempParams(), and XLoader_ProcessAuthEncPrtn().
Referenced by XLoader_SecureInit().
int XLoader_SecureValidations (const XLoader_SecureParams * SecurePtr)
This function checks if authentication/encryption is compulsory.
Parameters
SecurePtr is pointer to the XLoader_SecureParams instance.
Returns
XST_SUCCESS on success and error code on failure
Check Secure State of device If A-HWROT is enabled then authentication is mandatory for metaheader and BHDR authentication must be disabled
Check Secure State of the device. If S-HWRoT is enabled, then metaheader must be encrypted
Verify if Metaheader encryption key source for FPDI/PPDI is same as PLM Key source in Bootheader
References XLoader_GetAHWRoT(), XLoader_GetSHWRoT(), and XLoader_GetTempParams().